In [9]:
from mytools import complement, reverse_complement, my_translate, six_frames

In [10]:
gene = open("xyl_full.txt").read()
print(len(gene))

682

In [11]:
gene = open("xyl_full.txt").read().strip()

In [12]:
print(len(gene))

682

In [38]:
frames = six_frames(gene)
print(len(frames))
print(max(frames, key=len))

6
ILKEVIMFKFKKNFLVGLSAALMSISLFSATASAASTDYWQNWTDGGGIVNAVNGSGGNYSVNWSNTGNFVVGKGWTTGSPFRTINYNAGVWAPNGNGYLTLYGWTRSPLIEYYVVDSWGTYRPTGTYKGTVKSDGGTYDIYTTTRYNAPSIDGDRTTFTQYWSVRQSKRPTGSNATITFTNHVNAWKSHGMNLGSNWAYQVMATEGYQSSGSSNVTVW

In [26]:
open("my_protein.txt", "w").write("MFKFKKNFLV")

10

In [27]:
protein = frames[2]
start = protein.find("M")      # where's the first M?
orf = protein[start:]          # cut off the junk before it
print(len(orf))
print(orf[:20])
open("xylanase_protein.txt", "w").write(orf)

213
MFKFKKNFLVGLSAALMSIS

213

In [28]:
check = open("xylanase_protein.txt").read()
print(len(check))
print(check == orf)

213
True

In [29]:
open("xylanase.fasta", "w").write(">xylanase_ORF\n" + orf + "\n")

228

In [30]:
import os
print(os.getcwd())
print(os.listdir())

C:\Users\jad\DIPLOMOVA PRACA\learning\lesson 4
['.ipynb_checkpoints', 'frames.ipynb', 'mytools.py', 'my_protein.txt', 'Untitled.ipynb', 'xylanase.fasta', 'xylanase_protein.txt', 'xyl_full.txt', '__pycache__']

In [34]:
print(open("xylanase.fasta").read())

>xylanase_ORF
MFKFKKNFLVGLSAALMSISLFSATASAASTDYWQNWTDGGGIVNAVNGSGGNYSVNWSNTGNFVVGKGWTTGSPFRTINYNAGVWAPNGNGYLTLYGWTRSPLIEYYVVDSWGTYRPTGTYKGTVKSDGGTYDIYTTTRYNAPSIDGDRTTFTQYWSVRQSKRPTGSNATITFTNHVNAWKSHGMNLGSNWAYQVMATEGYQSSGSSNVTVW

In [42]:
lengths = []
for f in frames:
    lengths.append(len(f))

print(lengths)

[5, 2, 219, 18, 10, 13]

In [43]:
import pandas as pd

labels = ["fwd 0", "fwd 1", "fwd 2", "rev 0", "rev 1", "rev 2"]

df = pd.DataFrame({"frame": labels, "length": lengths, "protein": frames})
df

   frame  length                                            protein
0  fwd 0       5                                              GSLRR
1  fwd 1       2                                                 DP
2  fwd 2     219  ILKEVIMFKFKKNFLVGLSAALMSISLFSATASAASTDYWQNWTDG...
3  rev 0      18                                 SVPSFCSYQTVTLDEPLD
4  rev 1      10                                         RYQASAVTKP
5  rev 2      13                                      GTKLLQLPNRDVG

In [63]:
df.sort_values("length")
df.head()                 
df.to_csv("frames.csv")

In [73]:
df.sort_values("length", ascending=False)

   frame  length                                            protein
2  fwd 2     219  ILKEVIMFKFKKNFLVGLSAALMSISLFSATASAASTDYWQNWTDG...
3  rev 0      18                                 SVPSFCSYQTVTLDEPLD
5  rev 2      13                                      GTKLLQLPNRDVG
4  rev 1      10                                         RYQASAVTKP
0  fwd 0       5                                              GSLRR
1  fwd 1       2                                                 DP

In [74]:
df.to_csv("frames.csv", index=False)